#location,tool_name,severity,redundancy_level,neighbors,category,clang-analyzer,frama-c,cppcheck,flawfinder,label
library(fastAdaboost)
raw_data <- read.csv("features.csv", header=TRUE, sep=",")
print("begin training")
test_adaboost<-adaboost(label~tool_name+severity+redundancy_level+neighbors+category+clang_analyzer+frama_c+cppcheck+flawfinder, raw_data, 10000)
print("end training")
print("begin predictions")
pred <- predict( test_adaboost,newdata=raw_data)
print("end predictions")
print("printing adaboost")
print(test_adaboost)
print("end printing adaboost")
print("ERROR:")
print(pred$error)
print("END")
